[package]
name = "market-time-desktop"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[build-dependencies]
tauri-build = { version = "2.5.4", features = [] }
url = "2.5.8"

[dependencies]
tauri = { version = "=2.11.5", features = ["tray-icon"] }
tauri-plugin-notification = "=2.3.3"

[dev-dependencies]
url = "2.5.8"
